### ISSUE TITLE
4. авторизация

### ISSUE THREAD

**Issue by mshinkareva** [mshinkareva/Auth_sprint_1#29]
Я бы рекомендовал отказаться от авторизации по имени пользователя и использовать адрес электронной почты. Наша задача сделать максимально простую регистрацию для пользователя. Почты у всех уникальные, а придумывать имя пользователя - то еще приключение. Вспомните когда от вас требовалось при регистрации на коком-либо ресурсе придумывать имя пользователя. Наверняка это было давно и редко, и сколько раз приходилось изменять имя пользователя, т.к. оно уже занято, и сколько раз вы хотели все бросить и уйти с этого ресурса

**Comment by ceratuz** [comment]
https://github.com/mshinkareva/Auth_sprint_1/pull/40
