### ISSUE TITLE
5. вынести значение в переменные окружения

### ISSUE THREAD

**Issue by mshinkareva** [mshinkareva/Auth_sprint_1#30]
В auth-service/app/src/main.py в конструкции 
 postgres.engine = AsyncEngine(
         create_engine(settings.pg_url(), echo=True, future=True)
     )
  
 Значение параметра echo лучше вынести в настройки и переменную окружение, нам не всегда нужны логи запросов в базу данных, а он именно за это отвечает

**Comment by ceratuz** [comment]
PR - https://github.com/mshinkareva/Auth_sprint_1/pull/42
