### ISSUE TITLE
10 Relationship

### ISSUE THREAD

**Issue by mshinkareva** [mshinkareva/Auth_sprint_1#33]
В моделях базы данных не определено ни одного внешнего ключа и нет связей никаких (Relationship). Так будет очень сложно строить и развивать приложение. https://sqlmodel.tiangolo.com/tutorial/relationship-attributes/define-relationships-attributes/

**Comment by ceratuz** [comment]
PR - https://github.com/mshinkareva/Auth_sprint_1/pull/43
