### ISSUE TITLE
12 декоратор для авторизации

### ISSUE THREAD

**Issue by mshinkareva** [mshinkareva/Auth_sprint_1#35]
Сначала написал п.11, а потом увидел, что у вас вообще ВСЕ доступно всем, даже без какой-либо авторизации. Например, управление пользователями и ролями должно быть только у админа. А у меня без авторизации получилось создать роль. Лучше проверку прав делать в виде декоратора для эндпоинта, так сразу видно кому что разрешено.

**Comment by ceratuz** [comment]
пример от наставника https://gist.github.com/RomanAVolodin/e2731b303ef8b3c29d1052e82d5a7b36
